[package]
name = "workflow-rs"
version = "0.1.0"
edition = "2024"

[workspace]
members = ["workflow_macros", "."]

[dependencies]
async-trait = "0.1"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
thiserror = "2"
tokio = { version = "1", features = ["full"] }
once_cell = "1"
uuid = { version = "1", features = ["v4"] }
workflow_macros = { path = "./workflow_macros" }
