[package]
name = "model-client"
version = "0.1.0"
edition = "2024"

[dependencies]
async-trait.workspace = true
serde.workspace = true
serde_json.workspace = true
service_utils_rs.workspace = true

workflow-error = { path = "../workflow-error" }
