[package]
name = "workflow-error"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror.workspace = true
tokio.workspace = true
serde_json.workspace = true
service_utils_rs.workspace = true
mcp-error.workspace = true
